pipeline {
    agent any

    tools {
        maven 'Maven'
        jdk 'Java 8'
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/pravendrakumar777/rcm-engineering', branch: 'main'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }
        stage('Run') {
            steps {
                sh 'java -jar target/rcm-engineering-0.0.1-SNAPSHOT.jar &'
            }
        }
    }
}